FROM golang:1.23

RUN go install github.com/air-verse/air@v1.61.1

WORKDIR /src/presentation

COPY ./.air.unx.toml /.air.unx.toml
COPY ./src /src

RUN chmod -R 777 /src
RUN go mod tidy

CMD ["air", "-c", "../../.air.unx.toml"]
